# Generated by Django 4.2.7 on 2023-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=20)),
                ('operator_side', models.CharField(choices=[('attacker', 'attacker'), ('defender', 'defender')], max_length=20)),
                ('operator_speed', models.IntegerField()),
                ('operator_armor', models.IntegerField()),
            ],
        ),
    ]
