# Generated by Django 4.2.7 on 2023-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranked', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='operator_health',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
