# Generated by Django 4.2.7 on 2023-11-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranked', '0002_operator_operator_health'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operator',
            old_name='operator_armor',
            new_name='operator_difficulty',
        ),
    ]
