# Generated by Django 4.2.7 on 2023-11-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranked', '0004_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='operator_difficulty',
        ),
    ]
